server.port=4005

spring.datasource.url=jdbc:mysql://localhost:3306/patient_authentication_db
spring.datasource.username=root
spring.datasource.password=Starfield@007

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always

spring.defer-datasource-initialization=true