server.port=4005

spring.datasource.url=jdbc:mysql://auth-service-db:3306/patient-authentication-db
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

#data.sql to execute
spring.sql.init.mode=always

spring.defer-datasource-initialization=true

#JWT config
jwt.secret=6273bec2d16f1e735fbe923aa99cd1809b14fd02bf226392931a4618a3a5988c