server:
  port: 4004
  netty:
    access-log:
      enabled: true

#auth:
#  service:
#    url: http://auth-service:4005
##Docker config
#spring:
#  cloud:
#    gateway:
#
#      routes:
#        - id: auth-service-route
#          uri: http://auth-service:4005
#          predicates:
#            - Path=/auth/**
#          filters:
#            - StripPrefix=1
#
#        - id: patient-service-route
#          uri: http://patient-service:4000
#          predicates:
#            - Path=/api/patients/**
#          filters:
#            - JwtValidation
#
#        - id: api-docs-patient-route
#          uri: http://patient-service:4000
#          predicates:
#            - Path=/api-docs/patients
#          filters:
#            - RewritePath=/api-docs/patients,/v3/api-docs
#
#        - id: api-docs-auth-route
#          uri: http://auth-service:4005
#          predicates:
#            - Path=/api-docs/auth
#          filters:
#            - RewritePath=/api-docs/auth,/v3/api-docs
#
#        - id: api-docs-favicon-patient
#          uri: http://patient-service:4000
#          predicates:
#            - Path=/favicon.ico
#
#        - id: api-docs-favicon-auth
#          uri: http://auth-service:4005
#          predicates:
#            - Path=/favicon.ico
#


auth:
  service:
    url: http://localhost:4005
#local config
spring:
  cloud:
    gateway:
      enabled: true
      routes:

        - id: auth-service-route
          uri: http://localhost:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: patient-service-route
          uri: http://localhost:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - JwtValidation

        - id: api-docs-patient-route
          uri: http://localhost:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://localhost:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

        - id: api-docs-favicon-patient
          uri: http://localhost:4000
          predicates:
              - Path=/favicon.ico

        - id: api-docs-favicon-auth
          uri: http://localhost:4005
          predicates:
            - Path=/favicon.ico

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO
    org.springframework.web: DEBUG